name: E2E Tests

env:
  ENABLE_E2E: 'false'

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  e2e-tests:
    if: ${{ false }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.0'
          registry-url: 'https://registry.npmjs.org'
          always-auth: true
          cache: 'npm'

      - name: Force Node 20 environment
        run: |
          echo "PATH=/opt/hostedtoolcache/node/20.19.0/x64/bin:$PATH" >> $GITHUB_ENV
          echo "NODE_VERSION=20.19.0" >> $GITHUB_ENV
          
      - name: Verify Node version (must be 20.x)
        run: |
          echo "Node version: $(node -v)"
          echo "NPM version: $(npm -v)"
          node -v | grep -E '^v20\.' || (echo "ERROR: Node 20 required but got $(node -v)" && exit 1)
          npm -v | grep -E '^1(0|1)\.' || (echo "ERROR: NPM 10/11 required but got $(npm -v)" && exit 1)

      - name: Install system dependencies for Cypress
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libnss3-dev libxss1 libasound2-dev libxtst6 xauth

      - name: Create test .env file
        run: |
          echo "VITE_FIREBASE_API_KEY=fake" >> .env
          echo "VITE_FIREBASE_AUTH_DOMAIN=fake" >> .env
          echo "VITE_FIREBASE_PROJECT_ID=fake" >> .env
          echo "VITE_FIREBASE_STORAGE_BUCKET=fake" >> .env
          echo "VITE_FIREBASE_MESSAGING_SENDER_ID=fake" >> .env
          echo "VITE_FIREBASE_APP_ID=fake" >> .env
          echo "VITE_FIREBASE_MEASUREMENT_ID=fake" >> .env
          echo "MAILGUN_API_KEY=fake" >> .env
          echo "MAILGUN_DOMAIN=fake" >> .env

      - name: Install dependencies with engine-strict
        run: |
          npm cache clean --force
          npm ci --engine-strict

      - name: Start dev server and run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          start: npm run start:ci
          wait-on: 'http://localhost:5173'
          wait-on-timeout: 180
          browser: electron
          record: false
          spec: cypress/e2e/email/*.cy.js

      - name: Upload screenshots on failure
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore

      - name: Upload videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore
