name: E2E Tests

on:
  push:
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/browsers:node20.14.0-chrome126.0.6478.114-1-ff127.0.1-edge126.0.2592.68-1
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci --legacy-peer-deps --include=dev

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          start: npm run dev
          wait-on: 'http://localhost:5173'
          wait-on-timeout: 120
          browser: electron
          spec: 'cypress/e2e/email/tags-filters.cy.js'
        env:
          NODE_OPTIONS: "--experimental-vm-modules"
          CYPRESS_baseUrl: http://localhost:5173

      - name: Upload screenshots on failure
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore

      - name: Upload videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore
